apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
spec:
  selector:
    matchLabels:
      app: Python-app
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: Python-app
    spec:
      containers:
        - name: Python-app-container
          image: kedardesh7875/testing-images # Image that will be used to containers in the cluster
	  tag: latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000 # The port that the container is running on in the cluster

service:
  targetPort: 5000
  type: LoadBalancer
